"""remove certifications and other_requirements from job_requirements

Revision ID: 233a1442e4b8
Revises: ad5561826fc4
Create Date: 2026-03-01 19:50:55.272084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '233a1442e4b8'
down_revision: Union[str, Sequence[str], None] = 'ad5561826fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_requirements', 'certifications')
    op.drop_column('job_requirements', 'other_requirements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_requirements', sa.Column('other_requirements', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('job_requirements', sa.Column('certifications', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
