"""add interview mode and turn audio

Revision ID: 58982955eed3
Revises: 5be6e9496479
Create Date: 2026-08-08 21:34:04.619273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58982955eed3'
down_revision: Union[str, Sequence[str], None] = '5be6e9496479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_turns', sa.Column('audio_path', sa.Text(), nullable=True))
    op.add_column('interview_turns', sa.Column('audio_mime_type', sa.String(length=30), nullable=True))
    # answer_mode, not mode: `mode` is a Postgres COL_NAME_KEYWORD and a
    # qualified interviews.mode in a SELECT list fails to parse on PG 18.
    op.add_column('interviews', sa.Column('answer_mode', sa.String(length=10), server_default='text', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'answer_mode')
    op.drop_column('interview_turns', 'audio_mime_type')
    op.drop_column('interview_turns', 'audio_path')
    # ### end Alembic commands ###
