"""add interview tables

Revision ID: 5be6e9496479
Revises: 51896a764020
Create Date: 2026-08-02 17:36:01.459327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5be6e9496479'
down_revision: Union[str, Sequence[str], None] = '51896a764020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_id', sa.Uuid(), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('question_script', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grounding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('current_question_index', sa.Integer(), nullable=False),
    sa.Column('followup_asked', sa.Boolean(), nullable=False),
    sa.Column('last_seq', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.Column('assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assessment_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['candidate_evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_access_token'), 'interviews', ['access_token'], unique=True)
    op.create_index(op.f('ix_interviews_evaluation_id'), 'interviews', ['evaluation_id'], unique=True)
    op.create_table('interview_turns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id', 'seq', name='uq_interview_turn_seq')
    )
    op.create_index(op.f('ix_interview_turns_interview_id'), 'interview_turns', ['interview_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_turns_interview_id'), table_name='interview_turns')
    op.drop_table('interview_turns')
    op.drop_index(op.f('ix_interviews_evaluation_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_access_token'), table_name='interviews')
    op.drop_table('interviews')
    # ### end Alembic commands ###
