"""add interview voice mode

Revision ID: 5edfbfda4cc6
Revises: 58982955eed3
Create Date: 2026-08-09 21:01:36.196120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5edfbfda4cc6'
down_revision: Union[str, Sequence[str], None] = '58982955eed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('voice_mode', sa.String(length=3), server_default='off', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'voice_mode')
    # ### end Alembic commands ###
