"""drop responsibilities and keywords from jobs

Revision ID: ad5561826fc4
Revises: c16165848265
Create Date: 2026-02-28 22:17:00.701960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad5561826fc4'
down_revision: Union[str, Sequence[str], None] = 'c16165848265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'responsibilities')
    op.drop_column('jobs', 'keywords')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('keywords', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('responsibilities', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
