"""add foreign key indexes

Revision ID: c16165848265
Revises: 6efcdd13f5d0
Create Date: 2025-12-26 17:41:51.301044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c16165848265'
down_revision: Union[str, Sequence[str], None] = '6efcdd13f5d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_evaluation_run_items_candidate_id'), 'evaluation_run_items', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_evaluation_run_items_evaluation_id'), 'evaluation_run_items', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_evaluation_run_items_evaluation_run_id'), 'evaluation_run_items', ['evaluation_run_id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_job_id'), 'evaluation_runs', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluation_runs_job_id'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_run_items_evaluation_run_id'), table_name='evaluation_run_items')
    op.drop_index(op.f('ix_evaluation_run_items_evaluation_id'), table_name='evaluation_run_items')
    op.drop_index(op.f('ix_evaluation_run_items_candidate_id'), table_name='evaluation_run_items')
    # ### end Alembic commands ###
