"""add interview templates and draft approval gate

Revision ID: d6e838693ea4
Revises: e1d832eb2dda
Create Date: 2026-08-13 20:59:37.892245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6e838693ea4'
down_revision: Union[str, Sequence[str], None] = 'e1d832eb2dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_run_id', sa.Uuid(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('followups_enabled', sa.Boolean(), nullable=False),
    sa.Column('opening', sa.Text(), nullable=True),
    sa.Column('closing', sa.Text(), nullable=True),
    sa.Column('fixed_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_templates_evaluation_run_id'), 'interview_templates', ['evaluation_run_id'], unique=True)
    op.add_column('interviews', sa.Column('followups_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('interviews', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.alter_column('interviews', 'access_token',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('interviews', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drafts only exist under the new schema and have neither token nor expiry,
    # so they cannot survive the NOT NULL restore below. Drop them first --
    # they are unapproved and were never reachable by a candidate, so nothing
    # is lost that anyone has seen.
    op.execute("DELETE FROM interviews WHERE status = 'draft'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interviews', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('interviews', 'access_token',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('interviews', 'approved_at')
    op.drop_column('interviews', 'followups_enabled')
    op.drop_index(op.f('ix_interview_templates_evaluation_run_id'), table_name='interview_templates')
    op.drop_table('interview_templates')
    # ### end Alembic commands ###
