"""add deletion_audits table

Revision ID: e1d832eb2dda
Revises: 9a3c1f7b42de
Create Date: 2026-08-12 22:11:55.922322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1d832eb2dda'
down_revision: Union[str, Sequence[str], None] = '9a3c1f7b42de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # target_id and run_id are deliberately not foreign keys: they name rows
    # that no longer exist by the time the audit is read. actor_user_id is a FK
    # but SET NULL, so removing an account cannot erase the record of what it
    # deleted -- actor_email is the surviving identification.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deletion_audits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deletion_audits_actor_user_id'), 'deletion_audits', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_deletion_audits_created_at'), 'deletion_audits', ['created_at'], unique=False)
    op.create_index(op.f('ix_deletion_audits_run_id'), 'deletion_audits', ['run_id'], unique=False)
    op.create_index(op.f('ix_deletion_audits_target_id'), 'deletion_audits', ['target_id'], unique=False)
    op.create_index(op.f('ix_deletion_audits_target_type'), 'deletion_audits', ['target_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deletion_audits_target_type'), table_name='deletion_audits')
    op.drop_index(op.f('ix_deletion_audits_target_id'), table_name='deletion_audits')
    op.drop_index(op.f('ix_deletion_audits_run_id'), table_name='deletion_audits')
    op.drop_index(op.f('ix_deletion_audits_created_at'), table_name='deletion_audits')
    op.drop_index(op.f('ix_deletion_audits_actor_user_id'), table_name='deletion_audits')
    op.drop_table('deletion_audits')
    # ### end Alembic commands ###
