"""add interview time limit

Revision ID: f640645dd32b
Revises: d6e838693ea4
Create Date: 2026-08-14 22:41:40.252588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f640645dd32b'
down_revision: Union[str, Sequence[str], None] = 'd6e838693ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_templates', sa.Column('time_limit_seconds', sa.Integer(), server_default='900', nullable=False))
    op.add_column('interviews', sa.Column('time_limit_seconds', sa.Integer(), server_default='900', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'time_limit_seconds')
    op.drop_column('interview_templates', 'time_limit_seconds')
    # ### end Alembic commands ###
